name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: waka_0a08ab7c-392d-467c-ba79-c9f67430f23f
          GH_TOKEN: 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
          # 时间线
          SHOW_LOC_CHART: False
